# ~/.config/kitty/kitty.conf

# Font settings
font_family Hack Nerd Font
bold_font Hack Nerd Font
italic_font Hack Nerd Font
bold_italic_font Hack Nerd Font
font_size 10.0

# Line/character spacing (optional)
adjust_line_height 110%
adjust_column_width 102%

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Window appearance
background_opacity 0.20
enable_audio_bell no
hide_window_decorations no
window_border_width 0.5pt

# Colors
foreground   #ffffff
background   #0a0a0a
selection_foreground #1a1a1a
selection_background #c0c0c0

# Black, Red, Green, Yellow, Blue, Magenta, Cyan, White
color0  #000000
color1  #ff0000
color2  #00ff00
color3  #ffff00
color4  #0044ff
color5  #8800ff
color6  #00ffff
color7  #ffffff

color8  #444444
color9  #ff8888
color10 #88ff88
color11 #ffff88
color12 #8888ff
color13 #bb9af7
color14 #88ffff
color15 #cccccc

# Scrollback
scrollback_lines 5000

# Keybinding (optional)
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

